In the event that a function may throw an error or otherwise encounters an issue that breaks the normal function flow, we should use the `Result<T, E>` type in `types/functional`. To help with this, helper functions in `Ok` and `Err` exist at `utils/functional` to make the creation of these Results easy.

**Do not, under any circumstances, use `throw`!**

Throwing an error jumps out of the normal program execution, with no visible way of tracking that an error has been thrown outside of documentation (*hopefully*). This can cause issues if the function calling the throwing method fails to catch it, causing cascading failures higher up that should otherwise be handled. An uncaught undefined error in a small helper function can break an entire page.

# Handling Errors
Upon identifying a point of possible error, we should identify what should happen in the code if such an error does occur, then integrate that into the program flow. 

For example, if we are parsing XML and the XML is not valid, we should return an Err Result to the calling function. That calling function should understand that, yes, this is an error, mark it as such where appropriate (logs, a variable, etc), and either gracefully recover or return.